# Generated by Django 5.0.2 on 2024-02-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_api', models.CharField(max_length=1024, verbose_name='API мойсклад')),
                ('yandex_api', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='API Яндекс')),
                ('wildberries_api', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='API wildberries')),
                ('client_id', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Client Id Ozon')),
                ('ozon_api', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='API Ozon')),
                ('replenishment', models.BooleanField(default=False, verbose_name='Пополняется ли склад сейчас?')),
            ],
        ),
    ]
