# Generated by Django 3.1.4 on 2021-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PluginsCategory',
        ),
        migrations.RemoveField(
            model_name='plugins',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plugins',
            name='path',
        ),
        migrations.RemoveField(
            model_name='plugins',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plugins',
            name='is_migrate',
            field=models.BooleanField(default=False, verbose_name='Миграция'),
        ),
        migrations.AlterField(
            model_name='plugins',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='plugins',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Версия'),
        ),
    ]
