# Generated by Django 3.1.4 on 2021-02-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20210213_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugins',
            name='id_in_rep',
            field=models.IntegerField(blank=True, default=0, verbose_name='Id в репозитории'),
        ),
    ]
