# Generated by Django 3.1.4 on 2021-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_pluginscrm3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginscrm3',
            name='path',
            field=models.FileField(blank=True, upload_to='plugins/plugins/', verbose_name='Файл'),
        ),
    ]
