# Generated by Django 3.1.4 on 2021-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_auto_20210214_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_hash', models.CharField(max_length=10, verbose_name='Хэш')),
            ],
            options={
                'verbose_name': 'Связанные',
                'verbose_name_plural': 'Связанные данные',
            },
        ),
    ]
