# Generated by Django 3.1.4 on 2021-03-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_related'),
        ('plugins', '0006_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginsRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Связанные',
                'verbose_name_plural': 'Связанные данные',
            },
        ),
        migrations.DeleteModel(
            name='Related',
        ),
        migrations.AddField(
            model_name='plugins',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_plugin_related', to='plugins.plugins', verbose_name='Связь'),
        ),
        migrations.AddField(
            model_name='pluginsrelated',
            name='related',
            field=models.ManyToManyField(to='plugins.Plugins', verbose_name='Связь'),
        ),
    ]
