# Generated by Django 3.1.4 on 2021-03-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_auto_20210302_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugins',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_plugin_related', to='plugins.pluginsrelated', verbose_name='Связь'),
        ),
    ]
