# Generated by Django 3.1.4 on 2021-03-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0008_auto_20210302_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugins',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_plugin_related', to='plugins.plugins', verbose_name='Связь'),
        ),
        migrations.DeleteModel(
            name='PluginsRelated',
        ),
    ]
