# Generated by Django 3.1.4 on 2021-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_auto_20210304_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugins',
            name='related',
        ),
        migrations.AddField(
            model_name='plugins',
            name='related',
            field=models.ManyToManyField(related_name='_plugins_related_+', to='plugins.Plugins'),
        ),
    ]
