# Generated by Django 4.0.5 on 2022-07-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0011_plugins_related_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugins',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plugins',
            name='related',
            field=models.ManyToManyField(to='plugins.plugins'),
        ),
        migrations.AlterField(
            model_name='pluginscategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
