# Generated by Django 3.1.4 on 2021-03-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19)),
                ('prepayment', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('related_uuid', models.CharField(blank=True, max_length=22, verbose_name='uuid')),
            ],
            options={
                'verbose_name': 'Деньги',
                'verbose_name_plural': 'Деньги',
                'ordering': ['-created_at'],
            },
        ),
    ]
