# Generated by Django 4.0.5 on 2022-09-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Сумма')),
                ('prepayment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('related_uuid', models.JSONField(blank=True)),
            ],
            options={
                'verbose_name': 'Деньги',
                'verbose_name_plural': 'Деньги',
                'ordering': ['-created_at'],
            },
        ),
    ]
