# Generated by Django 3.1.4 on 2021-03-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19),
        ),
    ]
