# Generated by Django 4.1.1 on 2022-11-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='prepayment',
        ),
        migrations.RemoveField(
            model_name='money',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='money',
            name='updated_dict',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepayment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Предоплата')),
                ('comment', models.CharField(blank=True, max_length=150, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('money', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='prep_money', to='money.money', verbose_name='Prepay')),
            ],
            options={
                'verbose_name': 'Предоплата',
                'verbose_name_plural': 'Предоплата',
                'ordering': ['-created_at'],
            },
        ),
    ]
