# Generated by Django 4.1.1 on 2022-11-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_remove_money_prepayment_remove_money_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='updated_dict',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
