# Generated by Django 3.1.4 on 2021-03-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20210329_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='money',
            name='prepayment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='Предоплата'),
        ),
    ]
