# Generated by Django 3.1.4 on 2021-05-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20210330_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='related_uuid',
            field=models.JSONField(blank=True),
        ),
    ]
