# Generated by Django 4.1.1 on 2022-11-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_alter_prepayment_money_alter_prepayment_prepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='money',
            name='related_uuid',
            field=models.JSONField(),
        ),
    ]
