# Generated by Django 4.1.1 on 2022-12-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_relateduuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relateduuid',
            options={'ordering': ['pk'], 'verbose_name': 'uuid', 'verbose_name_plural': 'uuid'},
        ),
        migrations.RemoveField(
            model_name='relateduuid',
            name='related',
        ),
        migrations.AddField(
            model_name='money',
            name='uuid',
            field=models.ManyToManyField(to='money.relateduuid'),
        ),
    ]
