# Generated by Django 4.0.5 on 2022-09-14 01:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('contentform', ckeditor_uploader.fields.RichTextUploadingField()),
                ('related_uuid', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['-pk'],
            },
        ),
    ]
