# Generated by Django 3.1.4 on 2021-07-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_auto_20210722_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prints',
            options={'ordering': ['-pk'], 'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterField(
            model_name='prints',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='prints',
            name='related_uuid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
