# Generated by Django 3.1.4 on 2021-03-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='related',
        ),
        migrations.AddField(
            model_name='clients',
            name='related_uuid',
            field=models.CharField(blank=True, max_length=22, verbose_name='uuid'),
        ),
        migrations.DeleteModel(
            name='Related',
        ),
    ]
