# Generated by Django 4.1.1 on 2022-12-13 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_relateduuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relateduuid',
            options={'ordering': ['pk'], 'verbose_name': 'uuid', 'verbose_name_plural': 'uuid'},
        ),
        migrations.RemoveField(
            model_name='relateduuid',
            name='related',
        ),
        migrations.AddField(
            model_name='clients',
            name='uuid',
            field=models.ManyToManyField(to='clients.relateduuid'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79998887766'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
