# Generated by Django 3.1.4 on 2021-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименования категории'),
        ),
        migrations.AlterField(
            model_name='storehouses',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес'),
        ),
    ]
