# Generated by Django 3.1.4 on 2022-01-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0002_auto_20210922_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storehouses',
            name='related_uuid',
        ),
        migrations.CreateModel(
            name='StoreRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_uuid', models.JSONField(blank=True, null=True)),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_storehouse', to='storehouse.storehouses', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Формы',
                'ordering': ['-pk'],
            },
        ),
    ]
