# Generated by Django 4.0.5 on 2022-08-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0006_alter_category_id_alter_storehouses_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storerelated',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_storehouse', to='storehouse.storehouses', verbose_name='Отделение'),
        ),
    ]
