# Generated by Django 3.1.4 on 2021-03-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_related'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_related', to='plugins.related', verbose_name='Связь'),
        ),
        migrations.DeleteModel(
            name='Related',
        ),
    ]
