# Generated by Django 3.1.4 on 2021-02-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименования категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(db_index=True, max_length=150, verbose_name='Наименования категории')),
                ('related_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Связанные',
                'verbose_name_plural': 'Связанные данные',
                'ordering': ['plugin'],
            },
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='gadget',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_status', to='orders.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_category', to='orders.category', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orders',
            name='related',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_related', to='orders.related', verbose_name='Связь'),
        ),
    ]
