# Generated by Django 3.1.4 on 2021-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='status',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Наименования статуса'),
        ),
    ]
