# Generated by Django 3.1.4 on 2021-03-02 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210302_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='related',
        ),
    ]
