# Generated by Django 3.1.4 on 2021-05-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210501_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_device', to='orders.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='related_uuid',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_service', to='orders.service', verbose_name='Услуга'),
        ),
    ]
