# Generated by Django 4.1.1 on 2022-11-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_created_at_alter_orders_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_service',
            name='category',
        ),
        migrations.AlterField(
            model_name='category_service',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименования категории услуги'),
        ),
    ]
