# Generated by Django 3.1.4 on 2021-03-23 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_orders_related_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
