# Generated by Django 4.0.5 on 2022-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_category_service_alter_category_id_alter_device_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_service',
            options={'ordering': ['name'], 'verbose_name': 'Категория услуги', 'verbose_name_plural': 'Категории услуги'},
        ),
        migrations.RenameField(
            model_name='category_service',
            old_name='title',
            new_name='name',
        ),
    ]
