# Generated by Django 4.1.1 on 2022-12-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_relateduuid_related_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='related_uuid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
