# Generated by Django 4.0.5 on 2022-08-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_category_service_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_service',
            options={'ordering': ['name'], 'verbose_name': 'Категории услуги', 'verbose_name_plural': 'Категории услуги'},
        ),
    ]
