# Generated by Django 3.1.4 on 2021-03-30 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210330_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(default=1, max_length=150, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_category', to='orders.category', verbose_name='Категория'),
        ),
    ]
