# Generated by Django 4.1.1 on 2023-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_related_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='closed_status',
            field=models.BooleanField(default=True),
        ),
    ]
