# Generated by Django 4.1.1 on 2023-01-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_status_closed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='closed_status',
            field=models.BooleanField(default=False),
        ),
    ]
