# Generated by Django 4.0.5 on 2022-08-28 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_status_active_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_service',
            name='user_permission',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
