# Generated by Django 4.1.1 on 2023-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_status_closed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='#ffc700', max_length=7),
        ),
    ]
