# Generated by Django 4.0.5 on 2022-09-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_category_service_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='category_service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.category_service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='orders.category_service'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='get_category', to='orders.category', verbose_name='Категория приемки'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='category_service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='get_category_service', to='orders.category_service', verbose_name='Категория услуги'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='device',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='get_device', to='orders.device', verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='get_service', to='orders.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='get_status', to='orders.status', verbose_name='Статус'),
        ),
    ]
