# Generated by Django 4.1.1 on 2023-02-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_status_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='fast_closed',
            field=models.BooleanField(default=False),
        ),
    ]
