# Generated by Django 5.0.1 on 2024-01-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_status_fast_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
